# Generated by Django 4.2.6 on 2023-10-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_leavereportstaff_leave_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='attendace_id',
            new_name='attendance_id',
        ),
    ]
